In [422]:
import pandas as pd
import os

In [423]:
dust = pd.read_pickle("./mini-1/dust.pkl")
patient = pd.read_pickle("./mini-1/patients_num.pkl")

In [424]:
dust = dust.rename(index={'총계':'계','서울특별시':'서울','부산광역시':'부산',
                            '인천광역시':'인천','대구광역시':'대구','광주광역시':'광주',
                            '대전광역시':'대전','울산광역시':'울산','경기도':'경기','강원도':'강원',
                            '충청북도':'충북','충청남도':'충남','전라북도':'전북','전라남도':'전남',
                            '경상북도':'경북','경상남도':'경남','제주특별자치도':'제주','세종특별자치시':'세종'})
dust = dust.reindex(['계','서울','부산','인천','대구','광주',
              '대전','울산','경기','강원','충북','충남','전북',
              '전남','경북','경남','제주','세종'])

In [425]:
#1. index --> column 옮긴다.
dust = dust.reset_index()
#2. column명을 바꾼다.
dust = dust.rename(columns={'구분(1)' : '지역'})
#3. column --> index
dust = dust.set_index('지역')

In [426]:
dust = dust.T

In [427]:
dust

지역,계,서울,부산,인천,대구,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종
2019.10,32,31,27,35,27,35,29,27,37,28,33,38,34,27,31,30,32,32
2019.11,41,40,35,41,41,43,43,34,47,36,47,46,43,35,40,37,40,45
2019.12,39,42,35,40,42,33,40,33,47,37,46,42,36,28,39,33,29,46
2020.01,39,42,32,42,37,36,41,30,47,34,46,45,40,31,34,29,31,47
2020.02,38,41,34,37,38,32,38,31,44,36,42,44,36,31,35,32,34,43
2020.03,40,45,33,41,38,35,40,34,49,37,43,48,41,31,36,31,35,47
2020.04,41,44,36,39,39,38,41,36,47,39,43,45,41,34,38,33,41,44
2020.05,34,35,32,31,38,31,32,36,38,29,33,35,34,29,33,32,36,34
2020.06,34,36,27,32,35,31,34,32,41,35,36,35,36,26,32,29,27,37
2020.07,20,21,18,21,22,15,16,20,23,17,18,22,18,17,18,20,20,17
2020.08,24,23,31,24,25,22,20,28,24,19,21,24,22,28,23,29,29,20
2020.09,22,19,24,20,25,21,21,25,22,18,22,24,23,22,22,24,26,20
2020.10,34,33,30,34,33,31,33,30,38,28,36,39,35,28,31,29,31,35
2020.11,38,42,31,39,40,32,37,31,45,34,41,42,36,29,36,30,28,40
2020.12,38,42,33,39,38,33,38,30,46,36,44,42,36,28,36,30,24,44
2021.01,39,38,36,37,40,37,39,34,42,35,43,45,40,34,38,33,31,45
2021.02,43,48,37,46,41,40,42,35,52,39,46,52,42,35,40,33,34,47
2021.03,65,67,60,69,59,65,63,55,72,51,62,79,75,64,56,53,72,67
2021.04,41,42,37,42,42,39,41,37,46,38,41,46,43,34,42,34,36,42
2021.05,52,61,36,59,41,50,56,35,64,47,53,63,56,46,43,36,42,61
2021.06,32,33,26,36,35,29,31,28,37,24,32,34,36,27,31,27,25,31
2021.07,22,24,18,29,19,16,16,17,26,18,19,23,20,19,21,20,19,20
2021.08,21,22,19,22,21,17,18,20,25,19,21,23,20,20,23,20,17,21
2021.09,17,15,17,16,18,15,15,16,17,13,16,18,18,17,18,17,20,16
2021.10,27,27,23,28,26,25,27,22,31,19,30,32,31,24,25,23,24,29

In [428]:
dust.columns

Index(['계', '서울', '부산', '인천', '대구', '광주', '대전', '울산', '경기', '강원', '충북', '충남',
       '전북', '전남', '경북', '경남', '제주', '세종'],
      dtype='object', name='지역')

In [429]:
# patient = patient.reset_index()
# patient = patient.rename(columns={'지역' : '날짜'})
patient = patient.T

In [430]:
patient = patient.rename(columns={1:'총 환자 수',2:'서울 환자 수',3:'부산 환자 수',
                            4:'인천 환자 수',5:'대구 환자 수',6:'광주 환자 수',
                            7:'대전 환자 수',8:'울산 환자 수',9:'경기 환자 수',10:'강원 환자 수',
                            11:'충북 환자 수',12:'충남 환자 수',13:'전북 환자 수',14:'전남 환자 수',
                            15:'경북 환자 수',16:'경남 환자 수',17:'제주 환자 수',18:'세종 환자 수'})

In [431]:
dust = dust.rename(columns={'계':'전국 미세먼지 농도', '서울':'서울 먼지 농도', '부산':'부산 먼지 농도', '인천':'인천 먼지 농도', '대구':'대구 먼지 농도', 
                            '광주':'광주 먼지 농도', '대전':'대전 먼지 농도', '울산':'울산 먼지 농도', '경기':'경기 먼지 농도', '강원':'강원 먼지 농도',
                            '충북':'충북 먼지 농도', '충남':'충남 먼지 농도', '전북':'전북 먼지 농도', '전남':'전남 먼지 농도', '경북':'경북 먼지 농도',
                            '경남':'경남 먼지 농도', '제주':'제주 먼지 농도', '세종':'세종 먼지 농도'})

In [432]:
patient

,총 환자 수,서울 환자 수,부산 환자 수,인천 환자 수,대구 환자 수,광주 환자 수,대전 환자 수,울산 환자 수,경기 환자 수,강원 환자 수,충북 환자 수,충남 환자 수,전북 환자 수,전남 환자 수,경북 환자 수,경남 환자 수,제주 환자 수,세종 환자 수
지역,계,서울,부산,인천,대구,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종
2019.10,"8,420,041","1,651,751","549,988","476,490","388,517","266,658","277,537","196,465","2,250,270","220,491","271,048","353,295","301,130","275,841","384,469","531,581","117,507","65,578"
2019.11,"8,876,775","1,727,085","601,619","497,904","423,010","273,276","283,639","217,834","2,341,394","227,228","281,789","365,676","313,391","299,858","419,228","584,199","122,846","67,979"
2019.12,"10,114,677","1,964,570","684,773","573,766","484,563","302,958","320,097","244,482","2,698,006","258,753","311,795","410,038","362,909","339,472","486,458","674,959","140,324","77,498"
2020.01,"9,905,347","1,907,110","669,359","554,750","482,232","293,908","324,808","235,468","2,570,572","275,510","315,685","419,854","365,627","359,138","495,040","657,986","139,180","71,607"
2020.02,"6,293,450","1,190,445","438,312","338,664","312,377","183,978","211,980","158,530","1,493,086","172,267","209,329","264,102","240,867","245,238","332,637","451,946","94,353","44,518"
2020.03,"3,924,177","770,076","260,568","214,611","164,963","124,437","127,021","87,592","971,019","106,315","130,889","165,021","162,072","160,778","178,757","254,970","62,404","27,063"
2020.04,"3,214,874","613,213","206,569","166,704","143,364","110,084","103,775","70,591","793,240","89,072","108,644","135,341","138,937","132,105","150,203","203,819","60,524","22,234"
2020.05,"3,774,056","724,624","219,152","205,692","141,004","130,823","125,045","81,489","1,016,236","112,788","127,529","164,798","152,485","143,670","154,626","230,141","62,497","31,544"
2020.06,"3,716,173","666,557","255,212","187,449","153,099","124,479","126,201","92,532","959,275","107,877","125,212","166,103","148,443","138,221","172,829","244,963","57,878","33,335"
2020.07,"3,537,495","634,526","236,044","186,371","172,278","100,183","101,327","92,257","896,590","106,543","120,494","158,294","145,974","136,593","176,975","226,054","63,143","29,882"
2020.08,"3,046,704","561,718","197,854","157,515","143,849","89,210","103,116","74,274","766,365","89,816","108,297","133,197","128,113","110,458","148,290","195,921","56,138","26,911"
2020.09,"3,869,242","701,555","234,574","195,531","193,475","119,221","132,231","83,278","999,323","102,471","132,899","176,360","159,808","138,467","198,327","252,197","57,857","33,126"
2020.10,"4,356,416","735,050","271,761","229,951","229,439","154,413","145,042","97,464","1,100,541","120,171","144,823","197,444","181,480","166,360","219,291","304,816","68,745","40,348"
2020.11,"4,921,929","847,274","317,483","264,053","235,751","163,661","156,325","120,782","1,273,719","132,469","178,334","213,162","197,328","180,065","241,617","338,904","75,053","47,147"
2020.12,"3,725,686","639,403","246,785","190,755","199,415","121,633","129,682","92,034","902,298","101,701","126,482","169,368","151,866","141,484","201,194","249,753","68,526","33,260"
2021.01,"2,682,386","484,092","178,011","137,221","133,667","90,087","93,388","60,255","638,840","74,228","91,741","124,495","110,028","116,548","133,301","178,380","40,987","22,501"
2021.02,"2,738,737","482,881","187,805","139,307","133,295","87,174","94,200","64,873","654,459","75,797","96,682","125,087","113,748","114,486","134,938","189,559","50,234","22,311"
2021.03,"4,144,187","739,601","278,621","228,912","199,533","130,952","128,403","101,344","1,098,524","104,030","138,359","172,985","156,267","147,002","194,742","269,182","64,683","38,155"
2021.04,"4,786,581","895,335","292,809","254,015","259,459","147,720","149,012","116,460","1,286,799","118,595","155,886","200,122","166,348","166,627","233,574","291,981","68,691","43,169"
2021.05,"3,996,212","736,703","250,241","215,575","197,542","122,172","128,682","80,295","1,087,428","112,210","134,333","177,685","145,204","130,532","192,001","243,753","58,472","38,281"
2021.06,"3,554,168","641,100","225,028","190,924","164,514","110,694","117,324","75,975","946,995","95,750","122,143","159,567","143,023","116,733","172,453","228,129","50,453","35,484"
2021.07,"2,895,654","527,742","186,769","147,713","138,641","99,363","94,458","72,791","724,362","75,403","98,406","128,103","117,043","110,789","146,120","189,069","48,155","25,586"
2021.08,"2,628,365","488,460","173,103","132,022","135,163","87,998","82,531","62,862","649,952","75,819","93,639","118,064","105,220","89,481","133,817","161,188","44,315","23,556"
2021.09,"3,915,467","685,117","246,711","207,710","196,045","137,388","131,726","86,641","1,054,770","105,364","135,162","179,704","150,052","136,300","184,513","251,192","45,539","37,156"
2021.10,"4,726,771","793,596","324,029","247,765","235,812","157,016","158,138","120,947","1,222,209","125,000","160,989","205,937","184,720","165,888","236,483","329,615","79,483","44,908"

In [433]:
row_concat = pd.concat([dust, patient],axis=1, join='inner')

In [434]:
row_concat

,전국 미세먼지 농도,서울 먼지 농도,부산 먼지 농도,인천 먼지 농도,대구 먼지 농도,광주 먼지 농도,대전 먼지 농도,울산 먼지 농도,경기 먼지 농도,강원 먼지 농도,...,경기 환자 수,강원 환자 수,충북 환자 수,충남 환자 수,전북 환자 수,전남 환자 수,경북 환자 수,경남 환자 수,제주 환자 수,세종 환자 수
2019.10,32,31,27,35,27,35,29,27,37,28,...,"2,250,270","220,491","271,048","353,295","301,130","275,841","384,469","531,581","117,507","65,578"
2019.11,41,40,35,41,41,43,43,34,47,36,...,"2,341,394","227,228","281,789","365,676","313,391","299,858","419,228","584,199","122,846","67,979"
2019.12,39,42,35,40,42,33,40,33,47,37,...,"2,698,006","258,753","311,795","410,038","362,909","339,472","486,458","674,959","140,324","77,498"
2020.01,39,42,32,42,37,36,41,30,47,34,...,"2,570,572","275,510","315,685","419,854","365,627","359,138","495,040","657,986","139,180","71,607"
2020.02,38,41,34,37,38,32,38,31,44,36,...,"1,493,086","172,267","209,329","264,102","240,867","245,238","332,637","451,946","94,353","44,518"
2020.03,40,45,33,41,38,35,40,34,49,37,...,"971,019","106,315","130,889","165,021","162,072","160,778","178,757","254,970","62,404","27,063"
2020.04,41,44,36,39,39,38,41,36,47,39,...,"793,240","89,072","108,644","135,341","138,937","132,105","150,203","203,819","60,524","22,234"
2020.05,34,35,32,31,38,31,32,36,38,29,...,"1,016,236","112,788","127,529","164,798","152,485","143,670","154,626","230,141","62,497","31,544"
2020.06,34,36,27,32,35,31,34,32,41,35,...,"959,275","107,877","125,212","166,103","148,443","138,221","172,829","244,963","57,878","33,335"
2020.07,20,21,18,21,22,15,16,20,23,17,...,"896,590","106,543","120,494","158,294","145,974","136,593","176,975","226,054","63,143","29,882"
2020.08,24,23,31,24,25,22,20,28,24,19,...,"766,365","89,816","108,297","133,197","128,113","110,458","148,290","195,921","56,138","26,911"
2020.09,22,19,24,20,25,21,21,25,22,18,...,"999,323","102,471","132,899","176,360","159,808","138,467","198,327","252,197","57,857","33,126"
2020.10,34,33,30,34,33,31,33,30,38,28,...,"1,100,541","120,171","144,823","197,444","181,480","166,360","219,291","304,816","68,745","40,348"
2020.11,38,42,31,39,40,32,37,31,45,34,...,"1,273,719","132,469","178,334","213,162","197,328","180,065","241,617","338,904","75,053","47,147"
2020.12,38,42,33,39,38,33,38,30,46,36,...,"902,298","101,701","126,482","169,368","151,866","141,484","201,194","249,753","68,526","33,260"
2021.01,39,38,36,37,40,37,39,34,42,35,...,"638,840","74,228","91,741","124,495","110,028","116,548","133,301","178,380","40,987","22,501"
2021.02,43,48,37,46,41,40,42,35,52,39,...,"654,459","75,797","96,682","125,087","113,748","114,486","134,938","189,559","50,234","22,311"
2021.03,65,67,60,69,59,65,63,55,72,51,...,"1,098,524","104,030","138,359","172,985","156,267","147,002","194,742","269,182","64,683","38,155"
2021.04,41,42,37,42,42,39,41,37,46,38,...,"1,286,799","118,595","155,886","200,122","166,348","166,627","233,574","291,981","68,691","43,169"
2021.05,52,61,36,59,41,50,56,35,64,47,...,"1,087,428","112,210","134,333","177,685","145,204","130,532","192,001","243,753","58,472","38,281"
2021.06,32,33,26,36,35,29,31,28,37,24,...,"946,995","95,750","122,143","159,567","143,023","116,733","172,453","228,129","50,453","35,484"
2021.07,22,24,18,29,19,16,16,17,26,18,...,"724,362","75,403","98,406","128,103","117,043","110,789","146,120","189,069","48,155","25,586"
2021.08,21,22,19,22,21,17,18,20,25,19,...,"649,952","75,819","93,639","118,064","105,220","89,481","133,817","161,188","44,315","23,556"
2021.09,17,15,17,16,18,15,15,16,17,13,...,"1,054,770","105,364","135,162","179,704","150,052","136,300","184,513","251,192","45,539","37,156"
2021.10,27,27,23,28,26,25,27,22,31,19,...,"1,222,209","125,000","160,989","205,937","184,720","165,888","236,483","329,615","79,483","44,908"

In [435]:
row_concat.columns

Index(['전국 미세먼지 농도', '서울 먼지 농도', '부산 먼지 농도', '인천 먼지 농도', '대구 먼지 농도',
       '광주 먼지 농도', '대전 먼지 농도', '울산 먼지 농도', '경기 먼지 농도', '강원 먼지 농도', '충북 먼지 농도',
       '충남 먼지 농도', '전북 먼지 농도', '전남 먼지 농도', '경북 먼지 농도', '경남 먼지 농도', '제주 먼지 농도',
       '세종 먼지 농도', '총 환자 수', '서울 환자 수', '부산 환자 수', '인천 환자 수', '대구 환자 수',
       '광주 환자 수', '대전 환자 수', '울산 환자 수', '경기 환자 수', '강원 환자 수', '충북 환자 수',
       '충남 환자 수', '전북 환자 수', '전남 환자 수', '경북 환자 수', '경남 환자 수', '제주 환자 수',
       '세종 환자 수'],
      dtype='object')

In [436]:
row_concat

,전국 미세먼지 농도,서울 먼지 농도,부산 먼지 농도,인천 먼지 농도,대구 먼지 농도,광주 먼지 농도,대전 먼지 농도,울산 먼지 농도,경기 먼지 농도,강원 먼지 농도,...,경기 환자 수,강원 환자 수,충북 환자 수,충남 환자 수,전북 환자 수,전남 환자 수,경북 환자 수,경남 환자 수,제주 환자 수,세종 환자 수
2019.10,32,31,27,35,27,35,29,27,37,28,...,"2,250,270","220,491","271,048","353,295","301,130","275,841","384,469","531,581","117,507","65,578"
2019.11,41,40,35,41,41,43,43,34,47,36,...,"2,341,394","227,228","281,789","365,676","313,391","299,858","419,228","584,199","122,846","67,979"
2019.12,39,42,35,40,42,33,40,33,47,37,...,"2,698,006","258,753","311,795","410,038","362,909","339,472","486,458","674,959","140,324","77,498"
2020.01,39,42,32,42,37,36,41,30,47,34,...,"2,570,572","275,510","315,685","419,854","365,627","359,138","495,040","657,986","139,180","71,607"
2020.02,38,41,34,37,38,32,38,31,44,36,...,"1,493,086","172,267","209,329","264,102","240,867","245,238","332,637","451,946","94,353","44,518"
2020.03,40,45,33,41,38,35,40,34,49,37,...,"971,019","106,315","130,889","165,021","162,072","160,778","178,757","254,970","62,404","27,063"
2020.04,41,44,36,39,39,38,41,36,47,39,...,"793,240","89,072","108,644","135,341","138,937","132,105","150,203","203,819","60,524","22,234"
2020.05,34,35,32,31,38,31,32,36,38,29,...,"1,016,236","112,788","127,529","164,798","152,485","143,670","154,626","230,141","62,497","31,544"
2020.06,34,36,27,32,35,31,34,32,41,35,...,"959,275","107,877","125,212","166,103","148,443","138,221","172,829","244,963","57,878","33,335"
2020.07,20,21,18,21,22,15,16,20,23,17,...,"896,590","106,543","120,494","158,294","145,974","136,593","176,975","226,054","63,143","29,882"
2020.08,24,23,31,24,25,22,20,28,24,19,...,"766,365","89,816","108,297","133,197","128,113","110,458","148,290","195,921","56,138","26,911"
2020.09,22,19,24,20,25,21,21,25,22,18,...,"999,323","102,471","132,899","176,360","159,808","138,467","198,327","252,197","57,857","33,126"
2020.10,34,33,30,34,33,31,33,30,38,28,...,"1,100,541","120,171","144,823","197,444","181,480","166,360","219,291","304,816","68,745","40,348"
2020.11,38,42,31,39,40,32,37,31,45,34,...,"1,273,719","132,469","178,334","213,162","197,328","180,065","241,617","338,904","75,053","47,147"
2020.12,38,42,33,39,38,33,38,30,46,36,...,"902,298","101,701","126,482","169,368","151,866","141,484","201,194","249,753","68,526","33,260"
2021.01,39,38,36,37,40,37,39,34,42,35,...,"638,840","74,228","91,741","124,495","110,028","116,548","133,301","178,380","40,987","22,501"
2021.02,43,48,37,46,41,40,42,35,52,39,...,"654,459","75,797","96,682","125,087","113,748","114,486","134,938","189,559","50,234","22,311"
2021.03,65,67,60,69,59,65,63,55,72,51,...,"1,098,524","104,030","138,359","172,985","156,267","147,002","194,742","269,182","64,683","38,155"
2021.04,41,42,37,42,42,39,41,37,46,38,...,"1,286,799","118,595","155,886","200,122","166,348","166,627","233,574","291,981","68,691","43,169"
2021.05,52,61,36,59,41,50,56,35,64,47,...,"1,087,428","112,210","134,333","177,685","145,204","130,532","192,001","243,753","58,472","38,281"
2021.06,32,33,26,36,35,29,31,28,37,24,...,"946,995","95,750","122,143","159,567","143,023","116,733","172,453","228,129","50,453","35,484"
2021.07,22,24,18,29,19,16,16,17,26,18,...,"724,362","75,403","98,406","128,103","117,043","110,789","146,120","189,069","48,155","25,586"
2021.08,21,22,19,22,21,17,18,20,25,19,...,"649,952","75,819","93,639","118,064","105,220","89,481","133,817","161,188","44,315","23,556"
2021.09,17,15,17,16,18,15,15,16,17,13,...,"1,054,770","105,364","135,162","179,704","150,052","136,300","184,513","251,192","45,539","37,156"
2021.10,27,27,23,28,26,25,27,22,31,19,...,"1,222,209","125,000","160,989","205,937","184,720","165,888","236,483","329,615","79,483","44,908"